// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package server

import (
	"mcm-api/internal/core"
	"mcm-api/pkg/article"
	"mcm-api/pkg/authz"
	"mcm-api/pkg/comment"
	"mcm-api/pkg/contributesession"
	"mcm-api/pkg/contribution"
	"mcm-api/pkg/faculty"
	"mcm-api/pkg/media"
	"mcm-api/pkg/queue"
	"mcm-api/pkg/startup"
	"mcm-api/pkg/statistic"
	"mcm-api/pkg/systemdata"
	"mcm-api/pkg/user"
)

// Injectors from injector.go:

func InitializeServer() *Server {
	config := core.ProvideConfig()
	db := core.ProvideDB(config)
	repository := user.InitializeRepository(db)
	facultyRepository := faculty.InitializeRepository(db)
	service := faculty.InitializeService(config, facultyRepository)
	userService := user.InitializeService(config, repository, service)
	startupService := startup.InitializeStartUpService(userService)
	authzService := authz.InitializeAuthService(config, userService)
	handler := authz.NewAuthHandler(authzService)
	userHandler := user.NewUserHandler(config, userService)
	facultyHandler := faculty.NewHandler(config, service)
	imageProxyService := media.NewDarthsimImageProxyService(config)
	mediaService := media.NewStorageService(config, imageProxyService)
	mediaHandler := media.NewHandler(config, mediaService)
	contributesessionRepository := contributesession.InitializeRepository(db)
	client := core.ProvideRedis(config)
	queueQueue := queue.InitializeRedisQueue(config, client)
	contributesessionService := contributesession.InitializeService(config, contributesessionRepository, queueQueue, mediaService)
	contributesessionHandler := contributesession.NewHandler(config, contributesessionService)
	contributionRepository := contribution.InitializeRepository(db)
	articleRepository := article.InitializeRepository(db)
	articleService := article.InitializeService(config, articleRepository, mediaService, queueQueue)
	contributionService := contribution.InitializeService(config, contributionRepository, queueQueue, contributesessionService, articleService, mediaService)
	contributionHandler := contribution.NewHandler(config, contributionService)
	articleHandler := article.NewHandler(config, articleService)
	commentRepository := comment.InitializeRepository(db)
	commentService := comment.InitializeService(config, commentRepository, client, contributionService)
	commentHandler := comment.NewHandler(config, commentService)
	systemdataRepository := systemdata.InitializeRepository(db)
	systemdataService := systemdata.InitializeService(config, systemdataRepository)
	systemdataHandler := systemdata.NewHandler(config, systemdataService)
	statisticRepository := statistic.InitializeRepository(db)
	statisticService := statistic.InitializeService(statisticRepository, contributesessionService)
	statisticHandler := statistic.NewHandler(config, statisticService)
	server := newServer(config, startupService, handler, userHandler, facultyHandler, mediaHandler, contributesessionHandler, contributionHandler, articleHandler, commentHandler, systemdataHandler, statisticHandler)
	return server
}
