// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package worker

import (
	"mcm-api/internal/core"
	"mcm-api/pkg/article"
	"mcm-api/pkg/converter"
	"mcm-api/pkg/media"
	"mcm-api/pkg/queue"
)

// Injectors from injector.go:

func InitializeWorker() *worker {
	config := core.ProvideConfig()
	client := core.ProvideRedis(config)
	queueQueue := queue.InitializeRedisQueue(config, client)
	imageProxyService := media.NewDarthsimImageProxyService(config)
	service := media.NewStorageService(config, imageProxyService)
	documentConverter := converter.NewGotenbergDocumentConverter(config, service)
	db := core.ProvideDB(config)
	repository := article.InitializeRepository(db)
	articleService := article.InitializeService(config, repository, service, queueQueue)
	workerWorker := newWorker(config, queueQueue, documentConverter, articleService)
	return workerWorker
}
